Add simd feature, used with Hilbert block only so far
It only works on nightly as of 2025-01-06, but sped up Hilbert block
by 4.3x.

```
cargo +nightly build \
   --release \
   --example ax25-1200-rx \
&& ./target/release/examples/ax25-1200-rx \
  -a \
  -r cd/cd_tracks_01.au \
  --sample_rate 44100 \
  -o tmp
```

Before:

Block name         Seconds  Percent
-----------------------------------
FileSource           0.231    4.47%
AuDecode             0.069    1.34%
Hilbert              2.891   55.87%
QuadratureDemod      1.174   22.69%
FftFilterFloat       0.564   10.90%
add_const            0.010    0.20%
SymbolSync           0.198    3.83%
BinarySlicer         0.001    0.02%
NrziDecode           0.002    0.04%
HdlcDeframer         0.013    0.26%
PduWriter            0.020    0.39%
-----------------------------------
All blocks           5.174   99.99%
Non-block time       0.001    0.01%
Elapsed seconds      5.175  100.00%

After:
Block name         Seconds  Percent
-----------------------------------
FileSource           0.231    7.80%
AuDecode             0.084    2.84%
Hilbert              0.675   22.83%
QuadratureDemod      1.171   39.61%
FftFilterFloat       0.550   18.62%
add_const            0.010    0.34%
SymbolSync           0.201    6.79%
BinarySlicer         0.001    0.04%
NrziDecode           0.001    0.03%
HdlcDeframer         0.013    0.45%
PduWriter            0.019    0.64%
-----------------------------------
All blocks           2.956   99.98%
Non-block time       0.001    0.02%
Elapsed seconds      2.956  100.00%

Enabling all features brings total time down even further:

Block name         Seconds  Percent
-----------------------------------
FileSource           0.234   12.62%
AuDecode             0.085    4.62%
Hilbert              0.608   32.84%
QuadratureDemod      0.108    5.85%
FftFilterFloat       0.570   30.79%
add_const            0.011    0.60%
SymbolSync           0.199   10.78%
BinarySlicer         0.001    0.06%
NrziDecode           0.001    0.04%
HdlcDeframer         0.014    0.75%
PduWriter            0.020    1.06%
-----------------------------------
All blocks           1.851   99.96%
Non-block time       0.001    0.04%
Elapsed seconds      1.852  100.00%

diff --git a/extra/pre-commit b/extra/pre-commit
--- a/extra/pre-commit
+++ b/extra/pre-commit
@@ -31,15 +31,20 @@ cargo test || {
 
 # Test with all features.
 export CARGO_TARGET_DIR="$MAIN_DIR/target/test.all"
-cargo test --all-features || {
+cargo test --features rtlsdr,soapysdr,fast-math,audio || {
     echo "Tests fail with features" >&2
     exit 1
 }
 
 # Build with nightly.
 # TODO: maybe add --all-targets
-export CARGO_TARGET_DIR="$MAIN_DIR/target/nightly"
 cargo +nightly 2>/dev/null > /dev/null && {
+    export CARGO_TARGET_DIR="$MAIN_DIR/target/test.nightly.all"
+    cargo +nightly test --all-features || {
+	echo "Tests fail with features" >&2
+	exit 1
+    }
+    export CARGO_TARGET_DIR="$MAIN_DIR/target/nightly"
     cargo +nightly bench --no-run -F rtlsdr || {
 	echo "Benchmark builds fail" >&2
 	exit 1
