Run `cargo test` on commit

diff --git a/extra/precommit b/extra/precommit
--- a/extra/precommit
+++ b/extra/precommit
@@ -1,7 +1,11 @@
 #!/bin/bash
 
 cargo fmt -- --check || {
-    echo "Run: cargo fmt"
+    echo "Run: cargo fmt" >&2
+    exit 1
+}
+cargo test || {
+    echo "Tests fail" >&2
     exit 1
 }
 exit 0
