Add clippy to precommit

diff --git a/extra/precommit b/extra/precommit
--- a/extra/precommit
+++ b/extra/precommit
@@ -8,4 +8,8 @@ cargo test || {
     echo "Tests fail" >&2
     exit 1
 }
+cargo clippy -- -D warnings || {
+    echo "Clippy fail" >&2
+    exit 1
+}
 exit 0
